#pragma once
// Mate - libreria matematica didattica CV+
// Copyright (c) Alessandro Barazzuol

#include <algorithm>
#include <cmath>
#include <cctype>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <limits>
#include <map>
#include <memory>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace mate {

static constexpr const char* copyright = "Copyright (c) Alessandro Barazzuol";

inline std::string trim(std::string s){
    auto notsp=[](unsigned char c){return !std::isspace(c);};
    s.erase(s.begin(),std::find_if(s.begin(),s.end(),notsp));
    s.erase(std::find_if(s.rbegin(),s.rend(),notsp).base(),s.end());
    return s;
}
inline std::string rhs(std::string s){ auto p=s.find('='); if(p!=std::string::npos)s=s.substr(p+1); return trim(s); }
inline std::string jsesc(const std::string&s){std::string r;for(char c:s){if(c=='\\'||c=='\"'){r+='\\';r+=c;}else if(c=='\n')r+="\\n";else if(c!='\r')r+=c;}return r;}
inline std::string fmt(double v){ if(std::abs(v)<1e-12)v=0; std::ostringstream o;o<<std::setprecision(10)<<v;return o.str(); }

struct Node { enum Kind{Num,Var,Add,Sub,Mul,Div,Pow,Neg,Fun} k; double n=0; std::string s; std::shared_ptr<Node>a,b; };
using P=std::shared_ptr<Node>;
inline P num(double x){auto p=std::make_shared<Node>();p->k=Node::Num;p->n=x;return p;}
inline P var(std::string x){auto p=std::make_shared<Node>();p->k=Node::Var;p->s=std::move(x);return p;}
inline P un(Node::Kind k,P a,std::string s={}){auto p=std::make_shared<Node>();p->k=k;p->a=a;p->s=std::move(s);return p;}
inline P bin(Node::Kind k,P a,P b){auto p=std::make_shared<Node>();p->k=k;p->a=a;p->b=b;return p;}

class Parser{
    std::string q; size_t i=0;
    void ws(){while(i<q.size()&&std::isspace((unsigned char)q[i]))++i;}
    bool eat(char c){ws();if(i<q.size()&&q[i]==c){++i;return true;}return false;}
    std::string ident(){ws();size_t j=i;if(i<q.size()&&(std::isalpha((unsigned char)q[i])||q[i]=='_')){++i;while(i<q.size()&&(std::isalnum((unsigned char)q[i])||q[i]=='_'))++i;}return q.substr(j,i-j);}
    P primary(){ws(); if(eat('(')){auto x=expr();if(!eat(')'))throw std::runtime_error("Manca )");return x;} if(eat('-'))return un(Node::Neg,primary());
        ws(); if(i<q.size()&&(std::isdigit((unsigned char)q[i])||q[i]=='.')){char*e=nullptr;double v=std::strtod(q.c_str()+i,&e);i=(size_t)(e-q.c_str());return num(v);} 
        auto id=ident(); if(id.empty())throw std::runtime_error("Espressione non valida vicino a: "+q.substr(i));
        if(id=="pi"||id=="PI")return num(3.14159265358979323846); if(id=="e")return num(2.71828182845904523536);
        if(eat('(')){auto x=expr();if(!eat(')'))throw std::runtime_error("Manca ) dopo "+id);return un(Node::Fun,x,id);} return var(id);
    }
    P power(){auto x=primary(); if(eat('^')) x=bin(Node::Pow,x,power()); return x;}
    P term(){auto x=power();for(;;){if(eat('*'))x=bin(Node::Mul,x,power());else if(eat('/'))x=bin(Node::Div,x,power());else break;}return x;}
    P expr(){auto x=term();for(;;){if(eat('+'))x=bin(Node::Add,x,term());else if(eat('-'))x=bin(Node::Sub,x,term());else break;}return x;}
public: explicit Parser(std::string s):q(rhs(std::move(s))){} P parse(){auto x=expr();ws();if(i!=q.size())throw std::runtime_error("Testo inatteso: "+q.substr(i));return x;}
};

inline double eval(const P&p,const std::map<std::string,double>&v){
    switch(p->k){case Node::Num:return p->n;case Node::Var:{auto it=v.find(p->s);if(it==v.end())throw std::runtime_error("Variabile non valorizzata: "+p->s);return it->second;}
    case Node::Add:return eval(p->a,v)+eval(p->b,v);case Node::Sub:return eval(p->a,v)-eval(p->b,v);case Node::Mul:return eval(p->a,v)*eval(p->b,v);case Node::Div:return eval(p->a,v)/eval(p->b,v);case Node::Pow:return std::pow(eval(p->a,v),eval(p->b,v));case Node::Neg:return-eval(p->a,v);case Node::Fun:{double x=eval(p->a,v);auto f=p->s;if(f=="sin")return std::sin(x);if(f=="cos")return std::cos(x);if(f=="tan")return std::tan(x);if(f=="log"||f=="ln")return std::log(x);if(f=="exp")return std::exp(x);if(f=="sqrt")return std::sqrt(x);if(f=="abs")return std::abs(x);if(f=="asin")return std::asin(x);if(f=="acos")return std::acos(x);if(f=="atan")return std::atan(x);throw std::runtime_error("Funzione non supportata: "+f);}}
    return 0;
}
inline bool isnum(const P&p,double x){return p&&p->k==Node::Num&&std::abs(p->n-x)<1e-12;}
inline P simplify(P p){ if(!p)return p;if(p->a)p->a=simplify(p->a);if(p->b)p->b=simplify(p->b);
    if(p->k==Node::Neg&&p->a->k==Node::Num)return num(-p->a->n);
    if(p->b&&p->a->k==Node::Num&&p->b->k==Node::Num){std::map<std::string,double>m;try{return num(eval(p,m));}catch(...){}}
    if(p->k==Node::Add){if(isnum(p->a,0))return p->b;if(isnum(p->b,0))return p->a;} if(p->k==Node::Sub&&isnum(p->b,0))return p->a;
    if(p->k==Node::Mul){if(isnum(p->a,0)||isnum(p->b,0))return num(0);if(isnum(p->a,1))return p->b;if(isnum(p->b,1))return p->a;}
    if(p->k==Node::Div){if(isnum(p->a,0))return num(0);if(isnum(p->b,1))return p->a;} if(p->k==Node::Pow){if(isnum(p->b,1))return p->a;if(isnum(p->b,0))return num(1);} return p; }
inline int prec(const P&p){if(!p)return 9;switch(p->k){case Node::Add:case Node::Sub:return 1;case Node::Mul:case Node::Div:return 2;case Node::Pow:return 3;case Node::Neg:return 4;default:return 5;}}
inline std::string str(const P&p,int parent=0){if(!p)return"";std::string r;switch(p->k){case Node::Num:r=fmt(p->n);break;case Node::Var:r=p->s;break;case Node::Neg:r="-"+str(p->a,prec(p));break;case Node::Fun:r=p->s+"("+str(p->a)+")";break;case Node::Add:r=str(p->a,1)+" + "+str(p->b,1);break;case Node::Sub:r=str(p->a,1)+" - "+str(p->b,2);break;case Node::Mul:r=str(p->a,2)+"*"+str(p->b,2);break;case Node::Div:r=str(p->a,2)+"/"+str(p->b,3);break;case Node::Pow:r=str(p->a,3)+"^"+str(p->b,4);break;}if(prec(p)<parent)r="("+r+")";return r;}

inline P diff(const P&p,const std::string&x){switch(p->k){case Node::Num:return num(0);case Node::Var:return num(p->s==x?1:0);case Node::Add:return bin(Node::Add,diff(p->a,x),diff(p->b,x));case Node::Sub:return bin(Node::Sub,diff(p->a,x),diff(p->b,x));case Node::Mul:return bin(Node::Add,bin(Node::Mul,diff(p->a,x),p->b),bin(Node::Mul,p->a,diff(p->b,x)));case Node::Div:return bin(Node::Div,bin(Node::Sub,bin(Node::Mul,diff(p->a,x),p->b),bin(Node::Mul,p->a,diff(p->b,x))),bin(Node::Pow,p->b,num(2)));case Node::Neg:return un(Node::Neg,diff(p->a,x));case Node::Pow:if(p->b->k==Node::Num)return bin(Node::Mul,bin(Node::Mul,num(p->b->n),bin(Node::Pow,p->a,num(p->b->n-1))),diff(p->a,x));else return bin(Node::Mul,p,bin(Node::Add,bin(Node::Mul,diff(p->b,x),un(Node::Fun,p->a,"ln")),bin(Node::Mul,p->b,bin(Node::Div,diff(p->a,x),p->a))));case Node::Fun:{P d=diff(p->a,x);if(p->s=="sin")return bin(Node::Mul,un(Node::Fun,p->a,"cos"),d);if(p->s=="cos")return bin(Node::Mul,un(Node::Neg,un(Node::Fun,p->a,"sin")),d);if(p->s=="tan")return bin(Node::Mul,bin(Node::Div,num(1),bin(Node::Pow,un(Node::Fun,p->a,"cos"),num(2))),d);if(p->s=="ln"||p->s=="log")return bin(Node::Div,d,p->a);if(p->s=="exp")return bin(Node::Mul,un(Node::Fun,p->a,"exp"),d);if(p->s=="sqrt")return bin(Node::Div,d,bin(Node::Mul,num(2),un(Node::Fun,p->a,"sqrt")));break;}}throw std::runtime_error("Derivata simbolica non disponibile per questa funzione");}

inline bool linear_in(const P&p,const std::string&x,double&A,double&B){ // p=A*x+B
    if(p->k==Node::Var&&p->s==x){A=1;B=0;return true;} if(p->k==Node::Num){A=0;B=p->n;return true;}
    if(p->k==Node::Add||p->k==Node::Sub){double a1,b1,a2,b2;if(!linear_in(p->a,x,a1,b1)||!linear_in(p->b,x,a2,b2))return false;A=a1+(p->k==Node::Add?a2:-a2);B=b1+(p->k==Node::Add?b2:-b2);return true;}
    if(p->k==Node::Mul){if(p->a->k==Node::Num){double a,b;if(linear_in(p->b,x,a,b)){A=p->a->n*a;B=p->a->n*b;return true;}}if(p->b->k==Node::Num){double a,b;if(linear_in(p->a,x,a,b)){A=p->b->n*a;B=p->b->n*b;return true;}}} return false; }
inline bool depends(const P&p,const std::string&x){ if(!p)return false; if(p->k==Node::Var)return p->s==x; return depends(p->a,x)||depends(p->b,x); }
inline P integrate(const P&p,const std::string&x){
    if(p->k==Node::Num)return bin(Node::Mul,num(p->n),var(x)); if(p->k==Node::Var&&p->s==x)return bin(Node::Div,bin(Node::Pow,var(x),num(2)),num(2));
    if(p->k==Node::Add)return bin(Node::Add,integrate(p->a,x),integrate(p->b,x)); if(p->k==Node::Sub)return bin(Node::Sub,integrate(p->a,x),integrate(p->b,x)); if(p->k==Node::Neg)return un(Node::Neg,integrate(p->a,x));
    if(p->k==Node::Mul&&!depends(p->a,x))return bin(Node::Mul,p->a,integrate(p->b,x)); if(p->k==Node::Mul&&!depends(p->b,x))return bin(Node::Mul,p->b,integrate(p->a,x));
    if(p->k==Node::Div&&!depends(p->b,x))return bin(Node::Div,integrate(p->a,x),p->b);
    if(p->k==Node::Pow&&p->a->k==Node::Var&&p->a->s==x&&p->b->k==Node::Num){double n=p->b->n;if(std::abs(n+1)<1e-12)return un(Node::Fun,var(x),"ln");return bin(Node::Div,bin(Node::Pow,var(x),num(n+1)),num(n+1));}
    if(p->k==Node::Div&&isnum(p->a,1)&&p->b->k==Node::Var&&p->b->s==x)return un(Node::Fun,var(x),"ln");
    if(p->k==Node::Fun){double A,B;if(linear_in(p->a,x,A,B)&&std::abs(A)>1e-12){if(p->s=="sin")return bin(Node::Div,un(Node::Neg,un(Node::Fun,p->a,"cos")),num(A));if(p->s=="cos")return bin(Node::Div,un(Node::Fun,p->a,"sin"),num(A));if(p->s=="exp")return bin(Node::Div,un(Node::Fun,p->a,"exp"),num(A));}}
    throw std::runtime_error("Integrale simbolico non riconosciuto. Sono supportati somme, polinomi, 1/x, sin(a*x+b), cos(a*x+b), exp(a*x+b) e multipli costanti.");
}
inline std::string semplifica(const std::string&e){return str(simplify(Parser(e).parse()));}
inline std::string derivata(const std::string&e,const std::string&variabile="x"){return str(simplify(diff(Parser(e).parse(),variabile)));}
inline std::string integrale(const std::string&e,const std::string&variabile="x"){return str(simplify(integrate(Parser(e).parse(),variabile)))+" + C";}
inline double valore(const std::string&e,const std::map<std::string,double>&parametri){return eval(Parser(e).parse(),parametri);} 
inline double valore(const std::string&e,double x){return eval(Parser(e).parse(),{{"x",x}});} inline double valore(const std::string&e,double x,double y){return eval(Parser(e).parse(),{{"x",x},{"y",y}});}

inline std::vector<double> radici(const std::string&e,double xmin=-20,double xmax=20,int campioni=5000){P p=Parser(rhs(e)).parse();auto f=[&](double x){try{return eval(p,{{"x",x}});}catch(...){return std::numeric_limits<double>::quiet_NaN();}};std::vector<double>r;double px=xmin,py=f(px);for(int i=1;i<=campioni;i++){double x=xmin+(xmax-xmin)*i/campioni,y=f(x);if(std::isfinite(y)&&std::abs(y)<1e-8)r.push_back(x);if(std::isfinite(py)&&std::isfinite(y)&&py*y<0){double a=px,b=x,fa=py;for(int k=0;k<60;k++){double m=(a+b)/2,fm=f(m);if(fa*fm<=0)b=m;else{a=m;fa=fm;}}r.push_back((a+b)/2);}px=x;py=y;}std::sort(r.begin(),r.end());r.erase(std::unique(r.begin(),r.end(),[](double a,double b){return std::abs(a-b)<1e-5;}),r.end());return r;}
inline std::string risolvi_equazione(std::string eq,double xmin=-20,double xmax=20){auto p=eq.find('=');std::string e=eq;if(p!=std::string::npos)e="("+eq.substr(0,p)+")-("+eq.substr(p+1)+")";auto r=radici(e,xmin,xmax);if(r.empty())return"Nessuna soluzione reale trovata nell'intervallo ["+fmt(xmin)+", "+fmt(xmax)+"]";std::ostringstream o;o<<"x = ";for(size_t i=0;i<r.size();i++){if(i)o<<", ";o<<fmt(r[i]);}return o.str();}
inline std::string risolvi_disequazione(std::string q,double xmin=-20,double xmax=20){std::string op;size_t p=std::string::npos;for(auto s:{std::string(">="),std::string("<="),std::string(">"),std::string("<")}){p=q.find(s);if(p!=std::string::npos){op=s;break;}}if(p==std::string::npos)throw std::runtime_error("Usa >, <, >= oppure <=");std::string e="("+q.substr(0,p)+")-("+q.substr(p+op.size())+")";P n=Parser(e).parse();auto ok=[&](double x){double y=eval(n,{{"x",x}});return op==">"?y>0:op=="<"?y<0:op==">="?y>=0:y<=0;};auto rr=radici(e,xmin,xmax);std::vector<double>b{ xmin };b.insert(b.end(),rr.begin(),rr.end());b.push_back(xmax);std::ostringstream o;bool first=true;for(size_t i=0;i+1<b.size();i++){double a=b[i],c=b[i+1],m=(a+c)/2;if(ok(m)){if(!first)o<<" U ";o<<(op.size()==2?"[":"(")<<fmt(a)<<", "<<fmt(c)<<(op.size()==2?"]":")");first=false;}}return first?"Nessun intervallo soluzione":"x in "+o.str();}

inline std::pair<double,double> auto_range_1d(const P&p){double best=5;for(double R:{2.0,5.0,10.0,20.0}){int valid=0;double mx=0;for(int i=0;i<201;i++){double x=-R+2*R*i/200;try{double y=eval(p,{{"x",x}});if(std::isfinite(y)&&std::abs(y)<1e6){valid++;mx=std::max(mx,std::abs(y));}}catch(...){}}if(valid>160&&mx<500){best=R;break;}}return{-best,best};}
inline std::string html_head(const std::string&t){return "<!doctype html><html lang='it'><head><meta charset='utf-8'><title>Mate</title><style>html,body{margin:0;height:100%;background:#07111f;color:#eaf4ff;font-family:Segoe UI,Arial,sans-serif}#bar{height:64px;display:flex;align-items:center;justify-content:space-between;padding:0 22px;background:#0c1b30;border-bottom:1px solid #28496f;box-sizing:border-box}.title{font-size:20px;font-weight:700}.hint{font-size:12px;color:#9fc5ee}canvas{display:block}</style></head><body><div id='bar'><div><div class='title'>"+jsesc(t)+"</div><div class='hint'>Mate · libreria matematica CV+</div></div><div class='hint'>Copyright (c) Alessandro Barazzuol</div></div>";}
inline void open_html(const std::string&file){
#ifdef _WIN32
    std::string cmd="start \"\" \""+file+"\"";std::system(cmd.c_str());
#else
    (void)file;
#endif
}
inline void grafico2d(const std::string&formula,double xmin=std::numeric_limits<double>::quiet_NaN(),double xmax=std::numeric_limits<double>::quiet_NaN(),const std::string&titolo=""){
    P p=Parser(formula).parse();if(!std::isfinite(xmin)||!std::isfinite(xmax)||xmin>=xmax){auto r=auto_range_1d(p);xmin=r.first;xmax=r.second;}int N=900;std::vector<double>Y(N);double ymin=1e300,ymax=-1e300;for(int i=0;i<N;i++){double x=xmin+(xmax-xmin)*i/(N-1.0);try{Y[i]=eval(p,{{"x",x}});}catch(...){Y[i]=NAN;}if(std::isfinite(Y[i])&&std::abs(Y[i])<1e8){ymin=std::min(ymin,Y[i]);ymax=std::max(ymax,Y[i]);}}
    if(!std::isfinite(ymin)||!std::isfinite(ymax)){ymin=-1;ymax=1;}if(ymin>0)ymin=std::min(0.0,ymin);if(ymax<0)ymax=std::max(0.0,ymax);double pad=(ymax-ymin)*.12;if(pad<1e-6)pad=1;ymin-=pad;ymax+=pad;
    std::ofstream o("mate_grafico_2d.html");o<<html_head(titolo.empty()?formula:titolo)<<"<canvas id='c'></canvas><script>const xmin="<<xmin<<",xmax="<<xmax<<",ymin="<<ymin<<",ymax="<<ymax<<",Y=[";for(int i=0;i<N;i++){if(i)o<<',';if(std::isfinite(Y[i]))o<<std::setprecision(17)<<Y[i];else o<<"null";}o<<R"JS(];const c=document.getElementById('c'),g=c.getContext('2d');function X(x){return 55+(x-xmin)/(xmax-xmin)*(c.width-80)}function YP(y){return 20+(ymax-y)/(ymax-ymin)*(c.height-70)}function nice(v){let a=Math.abs(v);if(a>=1000||a<.001&&a>0)return v.toExponential(2);return (+v.toFixed(3)).toString()}function draw(){c.width=innerWidth*devicePixelRatio;c.height=(innerHeight-64)*devicePixelRatio;g.scale(devicePixelRatio,devicePixelRatio);let W=innerWidth,H=innerHeight-64;g.fillStyle='#07111f';g.fillRect(0,0,W,H);g.font='12px Segoe UI';g.strokeStyle='#203b5c';g.fillStyle='#9fc5ee';for(let i=0;i<=10;i++){let x=xmin+(xmax-xmin)*i/10,px=55+(W-80)*i/10;g.beginPath();g.moveTo(px,20);g.lineTo(px,H-50);g.stroke();g.fillText(nice(x),px-12,H-28)}for(let i=0;i<=8;i++){let y=ymin+(ymax-ymin)*i/8,py=20+(H-70)*(8-i)/8;g.beginPath();g.moveTo(55,py);g.lineTo(W-25,py);g.stroke();g.fillText(nice(y),7,py+4)}g.strokeStyle='#eaf4ff';g.lineWidth=2;if(xmin<=0&&xmax>=0){g.beginPath();g.moveTo(X(0)/devicePixelRatio,20);g.lineTo(X(0)/devicePixelRatio,H-50);g.stroke()}if(ymin<=0&&ymax>=0){g.beginPath();g.moveTo(55,YP(0)/devicePixelRatio);g.lineTo(W-25,YP(0)/devicePixelRatio);g.stroke()}g.strokeStyle='#31c8ff';g.lineWidth=2.4;g.beginPath();let started=false;for(let i=0;i<Y.length;i++){let y=Y[i];if(y===null){started=false;continue}let x=55+(W-80)*i/(Y.length-1),py=20+(ymax-y)/(ymax-ymin)*(H-70);if(!started){g.moveTo(x,py);started=true}else g.lineTo(x,py)}g.stroke();g.fillStyle='#fff';g.fillText('x',W-20,YP(0)/devicePixelRatio-7);g.fillText('y',X(0)/devicePixelRatio+7,15)}addEventListener('resize',draw);draw();</script></body></html>)JS";o.close();open_html("mate_grafico_2d.html");}

inline void grafico_integrale(const std::string&formula,double a,double b){
    P p=Parser(formula).parse();double xmin=std::min(a,b)-(std::abs(b-a)*.35+1),xmax=std::max(a,b)+(std::abs(b-a)*.35+1);int N=900;std::vector<double>Y(N);double ymin=0,ymax=0;for(int i=0;i<N;i++){double x=xmin+(xmax-xmin)*i/(N-1.0);try{Y[i]=eval(p,{{"x",x}});}catch(...){Y[i]=NAN;}if(std::isfinite(Y[i])){ymin=std::min(ymin,Y[i]);ymax=std::max(ymax,Y[i]);}}double pad=(ymax-ymin)*.12+1e-4;ymin-=pad;ymax+=pad;std::ofstream o("mate_integrale_area.html");o<<html_head("Area sotto la curva: "+formula)<<"<canvas id='c'></canvas><script>const xmin="<<xmin<<",xmax="<<xmax<<",ymin="<<ymin<<",ymax="<<ymax<<",A="<<a<<",B="<<b<<",Y=[";for(int i=0;i<N;i++){if(i)o<<',';if(std::isfinite(Y[i]))o<<Y[i];else o<<"null";}o<<R"JS(];const c=document.getElementById('c'),g=c.getContext('2d');function draw(){c.width=innerWidth;c.height=innerHeight-64;let W=c.width,H=c.height,X=x=>55+(x-xmin)/(xmax-xmin)*(W-80),P=y=>20+(ymax-y)/(ymax-ymin)*(H-70);g.fillStyle='#07111f';g.fillRect(0,0,W,H);g.strokeStyle='#24415f';for(let i=0;i<=10;i++){let x=xmin+(xmax-xmin)*i/10,px=X(x);g.beginPath();g.moveTo(px,20);g.lineTo(px,H-50);g.stroke();g.fillStyle='#9fc5ee';g.fillText((+x.toFixed(2)),px-10,H-28)}for(let i=0;i<=8;i++){let y=ymin+(ymax-ymin)*i/8,py=P(y);g.beginPath();g.moveTo(55,py);g.lineTo(W-25,py);g.stroke();g.fillText((+y.toFixed(2)),7,py+4)}let lo=Math.min(A,B),hi=Math.max(A,B);g.fillStyle='rgba(58,190,120,.35)';g.beginPath();g.moveTo(X(lo),P(0));for(let i=0;i<Y.length;i++){let x=xmin+(xmax-xmin)*i/(Y.length-1);if(x>=lo&&x<=hi&&Y[i]!=null)g.lineTo(X(x),P(Y[i]))}g.lineTo(X(hi),P(0));g.closePath();g.fill();g.strokeStyle='#36d8ff';g.lineWidth=2.5;g.beginPath();let st=0;for(let i=0;i<Y.length;i++){if(Y[i]==null){st=0;continue}let x=xmin+(xmax-xmin)*i/(Y.length-1);if(!st){g.moveTo(X(x),P(Y[i]));st=1}else g.lineTo(X(x),P(Y[i]))}g.stroke();g.strokeStyle='#fff';g.lineWidth=1.5;g.beginPath();g.moveTo(55,P(0));g.lineTo(W-25,P(0));g.stroke()}addEventListener('resize',draw);draw();</script></body></html>)JS";o.close();open_html("mate_integrale_area.html");}

inline void grafico_derivata(const std::string&formula,double x0){P p=Parser(formula).parse();P d=simplify(diff(p,"x"));double y0=eval(p,{{"x",x0}}),m=eval(d,{{"x",x0}});std::string tangent=fmt(y0)+" + ("+fmt(m)+")*(x-("+fmt(x0)+"))"; // genera pagina combinata
    double R=5,xmin=x0-R,xmax=x0+R;int N=900;std::vector<double>Y(N),T(N);double ymin=y0,ymax=y0;for(int i=0;i<N;i++){double x=xmin+(xmax-xmin)*i/(N-1.0);try{Y[i]=eval(p,{{"x",x}});}catch(...){Y[i]=NAN;}T[i]=y0+m*(x-x0);if(std::isfinite(Y[i])&&std::abs(Y[i])<1e5){ymin=std::min(ymin,Y[i]);ymax=std::max(ymax,Y[i]);}ymin=std::min(ymin,T[i]);ymax=std::max(ymax,T[i]);}double pad=(ymax-ymin)*.1+1e-3;ymin-=pad;ymax+=pad;std::ofstream o("mate_derivata_tangente_2d.html");o<<html_head("Tangente in x = "+fmt(x0)+" · f'(x) = "+str(d))<<"<canvas id='c'></canvas><script>const xmin="<<xmin<<",xmax="<<xmax<<",ymin="<<ymin<<",ymax="<<ymax<<",x0="<<x0<<",y0="<<y0<<",Y=[";for(int i=0;i<N;i++){if(i)o<<',';if(std::isfinite(Y[i]))o<<Y[i];else o<<"null";}o<<"],T=[";for(int i=0;i<N;i++){if(i)o<<',';o<<T[i];}o<<R"JS(];const c=document.getElementById('c'),g=c.getContext('2d');function draw(){c.width=innerWidth;c.height=innerHeight-64;let W=c.width,H=c.height,X=x=>55+(x-xmin)/(xmax-xmin)*(W-80),P=y=>20+(ymax-y)/(ymax-ymin)*(H-70);g.fillStyle='#07111f';g.fillRect(0,0,W,H);g.strokeStyle='#24415f';for(let i=0;i<=10;i++){let x=xmin+(xmax-xmin)*i/10,px=X(x);g.beginPath();g.moveTo(px,20);g.lineTo(px,H-50);g.stroke();g.fillStyle='#9fc5ee';g.fillText((+x.toFixed(2)),px-10,H-28)}for(let i=0;i<=8;i++){let y=ymin+(ymax-ymin)*i/8,py=P(y);g.beginPath();g.moveTo(55,py);g.lineTo(W-25,py);g.stroke();g.fillText((+y.toFixed(2)),7,py+4)}function plot(A,col,w){g.strokeStyle=col;g.lineWidth=w;g.beginPath();let s=0;for(let i=0;i<A.length;i++){if(A[i]==null){s=0;continue}let x=xmin+(xmax-xmin)*i/(A.length-1);if(!s){g.moveTo(X(x),P(A[i]));s=1}else g.lineTo(X(x),P(A[i]))}g.stroke()}plot(Y,'#31c8ff',2.5);plot(T,'#ffb347',2);g.fillStyle='#fff';g.beginPath();g.arc(X(x0),P(y0),5,0,7);g.fill()}addEventListener('resize',draw);draw();</script></body></html>)JS";o.close();open_html("mate_derivata_tangente_2d.html");}

inline void grafico3d(const std::string&formula,double xmin=NAN,double xmax=NAN,double ymin=NAN,double ymax=NAN,const std::string&titolo=""){
    P p=Parser(formula).parse();if(!std::isfinite(xmin)||!std::isfinite(xmax)||xmin>=xmax){xmin=-4;xmax=4;}if(!std::isfinite(ymin)||!std::isfinite(ymax)||ymin>=ymax){ymin=-4;ymax=4;}int N=55;std::vector<double>Z;Z.reserve(N*N);double zmin=1e300,zmax=-1e300;for(int j=0;j<N;j++){double y=ymin+(ymax-ymin)*j/(N-1.0);for(int i=0;i<N;i++){double x=xmin+(xmax-xmin)*i/(N-1.0),z;try{z=eval(p,{{"x",x},{"y",y}});}catch(...){z=NAN;}if(!std::isfinite(z)||std::abs(z)>1e7)z=NAN;Z.push_back(z);if(std::isfinite(z)){zmin=std::min(zmin,z);zmax=std::max(zmax,z);}}}if(!std::isfinite(zmin)){zmin=-1;zmax=1;}if(std::abs(zmax-zmin)<1e-9){zmin-=1;zmax+=1;}double zp=(zmax-zmin)*.08;zmin-=zp;zmax+=zp;
    std::ofstream o("mate_grafico_3d.html");o<<html_head(titolo.empty()?formula:titolo)<<R"HTML(<canvas id='c'></canvas><script>)HTML"<<"const N="<<N<<",xmin="<<xmin<<",xmax="<<xmax<<",ymin="<<ymin<<",ymax="<<ymax<<",zmin="<<zmin<<",zmax="<<zmax<<",Z=[";for(size_t k=0;k<Z.size();k++){if(k)o<<',';if(std::isfinite(Z[k]))o<<std::setprecision(17)<<Z[k];else o<<"null";}o<<R"JS(];const c=document.getElementById('c'),g=c.getContext('2d');let ax=-.72,ay=.72,zoom=1,drag=0,lx=0,ly=0;function P(x,y,z){let X=(x-(xmin+xmax)/2)/((xmax-xmin)/2),Y=(y-(ymin+ymax)/2)/((ymax-ymin)/2),Q=(z-(zmin+zmax)/2)/((zmax-zmin)/2),ca=Math.cos(ax),sa=Math.sin(ax),cb=Math.cos(ay),sb=Math.sin(ay),x1=X*cb-Q*sb,z1=X*sb+Q*cb,y2=Y*ca-z1*sa,s=Math.min(c.width,c.height)*.31*zoom;return[c.width/2+x1*s,c.height/2-y2*s]}function L(a,b,col,w=1){g.strokeStyle=col;g.lineWidth=w;g.beginPath();g.moveTo(...a);g.lineTo(...b);g.stroke()}function txt(t,p,col='#fff'){g.fillStyle=col;g.font='13px Segoe UI';g.fillText(t,p[0]+5,p[1]-5)}function draw(){c.width=innerWidth;c.height=innerHeight-64;g.fillStyle='#07111f';g.fillRect(0,0,c.width,c.height);for(let j=0;j<N;j++)for(let i=0;i<N-1;i++){let a=Z[j*N+i],b=Z[j*N+i+1];if(a!=null&&b!=null){let x1=xmin+(xmax-xmin)*i/(N-1),x2=xmin+(xmax-xmin)*(i+1)/(N-1),y=ymin+(ymax-ymin)*j/(N-1);let hue=190+80*(a-zmin)/(zmax-zmin);L(P(x1,y,a),P(x2,y,b),`hsla(${hue},85%,60%,.72)`,1)}}for(let i=0;i<N;i++)for(let j=0;j<N-1;j++){let a=Z[j*N+i],b=Z[(j+1)*N+i];if(a!=null&&b!=null){let x=xmin+(xmax-xmin)*i/(N-1),y1=ymin+(ymax-ymin)*j/(N-1),y2=ymin+(ymax-ymin)*(j+1)/(N-1);L(P(x,y1,a),P(x,y2,b),'rgba(80,170,240,.34)',.8)}}for(let k=0;k<=8;k++){let x=xmin+(xmax-xmin)*k/8;L(P(x,ymin,0),P(x,ymax,0),'rgba(150,180,210,.17)');let y=ymin+(ymax-ymin)*k/8;L(P(xmin,y,0),P(xmax,y,0),'rgba(150,180,210,.17)')}L(P(xmin,0,0),P(xmax,0,0),'#ff6b6b',3);L(P(0,ymin,0),P(0,ymax,0),'#56e39f',3);L(P(0,0,zmin),P(0,0,zmax),'#4db7ff',3);txt('X '+xmax.toFixed(2),P(xmax,0,0),'#ff9a9a');txt('Y '+ymax.toFixed(2),P(0,ymax,0),'#8ff0bd');txt('Z '+zmax.toFixed(2),P(0,0,zmax),'#8ed4ff');txt(xmin.toFixed(2),P(xmin,0,0),'#ff9a9a');txt(ymin.toFixed(2),P(0,ymin,0),'#8ff0bd');txt(zmin.toFixed(2),P(0,0,zmin),'#8ed4ff')}c.onmousedown=e=>{drag=1;lx=e.clientX;ly=e.clientY};onmouseup=()=>drag=0;onmousemove=e=>{if(!drag)return;ay+=(e.clientX-lx)*.008;ax+=(e.clientY-ly)*.008;lx=e.clientX;ly=e.clientY;draw()};c.onwheel=e=>{e.preventDefault();zoom*=e.deltaY<0?1.1:.9;zoom=Math.max(.3,Math.min(3,zoom));draw()};c.ondblclick=()=>{ax=-.72;ay=.72;zoom=1;draw()};addEventListener('resize',draw);draw();</script></body></html>)JS";o.close();open_html("mate_grafico_3d.html");}

inline void grafico_derivata3d(const std::string&formula,double x0,double y0){P p=Parser(formula).parse();P dx=simplify(diff(p,"x")),dy=simplify(diff(p,"y"));double z0=eval(p,{{"x",x0},{"y",y0}}),a=eval(dx,{{"x",x0},{"y",y0}}),b=eval(dy,{{"x",x0},{"y",y0}});std::string plane=fmt(z0)+" + ("+fmt(a)+")*(x-("+fmt(x0)+")) + ("+fmt(b)+")*(y-("+fmt(y0)+"))"; // pagina 3d con piano tangente come seconda mesh
    double xmin=x0-3,xmax=x0+3,ymin=y0-3,ymax=y0+3;int N=45;std::vector<double>Z,Q;double zmin=1e300,zmax=-1e300;for(int j=0;j<N;j++){double y=ymin+(ymax-ymin)*j/(N-1.0);for(int i=0;i<N;i++){double x=xmin+(xmax-xmin)*i/(N-1.0),z;try{z=eval(p,{{"x",x},{"y",y}});}catch(...){z=NAN;}double q=z0+a*(x-x0)+b*(y-y0);Z.push_back(z);Q.push_back(q);if(std::isfinite(z)){zmin=std::min(zmin,z);zmax=std::max(zmax,z);}zmin=std::min(zmin,q);zmax=std::max(zmax,q);}}double pad=(zmax-zmin)*.1+1e-3;zmin-=pad;zmax+=pad;std::ofstream o("mate_piano_tangente_3d.html");o<<html_head("Piano tangente: z = "+plane)<<"<canvas id='c'></canvas><script>const N="<<N<<",xmin="<<xmin<<",xmax="<<xmax<<",ymin="<<ymin<<",ymax="<<ymax<<",zmin="<<zmin<<",zmax="<<zmax<<",Z=[";for(size_t k=0;k<Z.size();k++){if(k)o<<',';if(std::isfinite(Z[k]))o<<Z[k];else o<<"null";}o<<"],Q=[";for(size_t k=0;k<Q.size();k++){if(k)o<<',';o<<Q[k];}o<<R"JS(];const c=document.getElementById('c'),g=c.getContext('2d');let ax=-.75,ay=.7,zoom=1,drag=0,lx,ly;function P(x,y,z){let X=(x-(xmin+xmax)/2)/((xmax-xmin)/2),Y=(y-(ymin+ymax)/2)/((ymax-ymin)/2),Q=(z-(zmin+zmax)/2)/((zmax-zmin)/2),ca=Math.cos(ax),sa=Math.sin(ax),cb=Math.cos(ay),sb=Math.sin(ay),x1=X*cb-Q*sb,z1=X*sb+Q*cb,y2=Y*ca-z1*sa,s=Math.min(c.width,c.height)*.31*zoom;return[c.width/2+x1*s,c.height/2-y2*s]}function L(a,b,col,w=1){g.strokeStyle=col;g.lineWidth=w;g.beginPath();g.moveTo(...a);g.lineTo(...b);g.stroke()}function mesh(A,col){for(let j=0;j<N;j++)for(let i=0;i<N-1;i++){let a=A[j*N+i],b=A[j*N+i+1];if(a!=null&&b!=null){let y=ymin+(ymax-ymin)*j/(N-1),x1=xmin+(xmax-xmin)*i/(N-1),x2=xmin+(xmax-xmin)*(i+1)/(N-1);L(P(x1,y,a),P(x2,y,b),col)}}for(let i=0;i<N;i++)for(let j=0;j<N-1;j++){let a=A[j*N+i],b=A[(j+1)*N+i];if(a!=null&&b!=null){let x=xmin+(xmax-xmin)*i/(N-1),y1=ymin+(ymax-ymin)*j/(N-1),y2=ymin+(ymax-ymin)*(j+1)/(N-1);L(P(x,y1,a),P(x,y2,b),col)}}}function draw(){c.width=innerWidth;c.height=innerHeight-64;g.fillStyle='#07111f';g.fillRect(0,0,c.width,c.height);mesh(Q,'rgba(255,180,65,.42)');mesh(Z,'rgba(50,205,255,.68)');L(P(xmin,0,0),P(xmax,0,0),'#ff6b6b',3);L(P(0,ymin,0),P(0,ymax,0),'#56e39f',3);L(P(0,0,zmin),P(0,0,zmax),'#4db7ff',3)}c.onmousedown=e=>{drag=1;lx=e.clientX;ly=e.clientY};onmouseup=()=>drag=0;onmousemove=e=>{if(!drag)return;ay+=(e.clientX-lx)*.008;ax+=(e.clientY-ly)*.008;lx=e.clientX;ly=e.clientY;draw()};c.onwheel=e=>{e.preventDefault();zoom*=e.deltaY<0?1.1:.9;draw()};addEventListener('resize',draw);draw();</script></body></html>)JS";o.close();open_html("mate_piano_tangente_3d.html");}

} // namespace mate
